apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
spec:
  template:
    spec:
      containers:
        - name: sidecar-injector
          env:
            - name: AGENT_INJECT_VAULT_ADDR
              value: https://vault-server:8200

